version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wanted-mysql
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wanted_root
      MYSQL_DATABASE: wanted
      MYSQL_USER: wanted_user
      MYSQL_PASSWORD: wanted_password
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      # 클라이언트 핸드쉐이크 무시하고 서버 설정 강제 (항상 utf8mb4로 통신)
      - --character-set-client-handshake=false
      # 최소 단어 길이를 1글자로 설정
      - --ft_min_word_len=1
      # (옵션) ngram 파서 토큰 크기를 1로 설정
      - --ngram_token_size=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
